---
- hosts: all
  user: pi
  become: true
  vars_files:
    - vars.yml
    
  tasks:
    - name: Enable ssh
      ansible.builtin.systemd: 
        name: ssh
        enabled: yes

    - name: Set hostname
      hostname:
        name: "{{inventory_hostname}}"

    - name: edit /etc/hosts
      lineinfile: 
        dest: /etc/hosts
        regexp: "^127.0.1.1"
        line: "127.0.1.1 {{inventory_hostname}}"
  
    - name:  Upgrade Raspbian
      apt:
        upgrade: full

    - name: Set correct timezone
      timezone:
        name: "{{time_zone}}"

    - name: Create locale
      locale_gen:
        name: "{{locale}}"
        state: present

    - name:  Create ansible status directory
      file:
        path: /opt/ansible/status
        state: directory
        mode: 0777

    - name: Set correct keyboard
      script: ./scripts/keyboard.sh "{{keyboard}}"
      args:
        creates: /opt/ansible/status/keyboard.ok

    - name: Install Python packages for ansible
      apt:
        name: python-apt

    - name: Install som basic packages
      apt:
        name:
        - "apt-transport-https"
        - "ca-certificates"
        - "software-properties-common"

    - name: Create user for kubernetes 
      user: 
        name: "{{kubernetes_user}}"
        comment: Kubernets User
        group: sudo
        shell: /bin/bash
        password: "$6$fP7bkLInNQtq$OX06Lzu7PJnH/G5l9JZf18itYSfhyDnA74TGFfNFRK8NNd84YOjzoQNdRSbDW.63cmCNTa1R3Moi4zvvialXq."


    - name:  Add authorized keys for Kubernetes user
      authorized_key:
        user: "{{kubernetes_user}}"
        state: present
        key: "{{pub_key}}"

    - name: Add nopass  sudo file for kubernetes user
      lineinfile:
        path: "/etc/sudoers.d/010_{{ kubernetes_user }}_nopasswd"
        create: yes
        line: "{{ kubernetes_user }} ALL=(ALL) NOPASSWD: ALL"
        owner: root

